layout_spectrum: 0.2992831
color:
  saturation: 0.5760543
  lightness: 0.2789446
  brandStrength: 0.9041118
  brandColors:
    - '#040404'
    - '#FFFFFF'
    - '#2B2821'
    - '#626970'
    - '#A69C92'
  rhythmicContrast: 0.9871686
typography_spectrum: 0.5824373
name: Ben Terry Lighting Design
